INSERT INTO LOCATION (loc_id, loc_name, loc_latitude, loc_longitude, loc_city, loc_province, loc_country, loc_postal) VALUES (seq_Location.nextval,'name',0.213,0.324,'Cape Town','Western Cape','South Africa','0766');
INSERT INTO SATELITE_VIEW (satelite_view_id, loc_id, satelite_view_url) VALUES (seq_SateliteView.nextval,1,'www.google.com');
INSERT INTO STREET (street_id, loc_id, street_name) VALUES (seq_Street.nextval,1,'street name');
INSERT INTO STREET_SEGMENT (segment_id, street_id, segment_length, segment_direction, segment_road_type, segment_start_loc_id, segment_end_loc_id) VALUES (seq_Segment.nextval,1,0.213,0.324,'Type',1,1);
INSERT INTO ROAD_EVENT (event_id, segment_id, event_type, event_start_datetime, event_end_datetime, event_description) VALUES (seq_Event.nextval,1,'Type',TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),'Description');
-- SELECT TO_CHAR(event_start_time, 'DD-MON-YYYY HH24:MI:SS') AS Start_Time FROM ROAD_EVENT;
INSERT INTO PUBLIC_TRANS_STOP (ptstop_id, segment_id, ptstop_name, ptstop_type, ptstop_loc_id) VALUES (seq_PTStop.nextval,1,'name','type',1);
INSERT INTO SPEED_LIMIT (slimit_id, segment_id, slimit_value, slimit_start_time, slimit_end_time) VALUES (seq_SpeedLimit.nextval,1,60,TO_DATE('21:02:44', 'hh24:mi:ss'),TO_DATE('21:02:44', 'hh24:mi:ss'));
-- SELECT TO_CHAR(slimit_start_time, 'HH24:MI:SS') AS Start_Time FROM SPEED_LIMIT;
INSERT INTO ROAD_OBJECT (object_id, segment_id, object_type, object_description, object_loc_id) VALUES (seq_RoadObject.nextval,1,'type','description',1);
INSERT INTO CONGESTION_LEVEL (congestion_id, congestion_type, congestion_description) VALUES (seq_Congestion.nextval,'type','description');
INSERT INTO TRAFFIC_DATA (tdata_id, segment_id, congestion_id, tdata_datetime, tdata_average_speed, tdata_traffic_volume) VALUES (seq_TrafficData.nextval,1,1,TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),60,10);
INSERT INTO TRAFFIC_CONDITION (traf_cond_id, segment_id, traf_cond_type, traf_cond_description, traf_cond_start_datetime, traf_cond_end_datetime) VALUES (seq_TrafficCond.nextval,1,'type','description',TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
-- SELECT TO_CHAR(traf_cond_start_date, 'DD-MON-YYYY HH24:MI:SS') AS Start_Time FROM TRAFFIC_CONDITION;
INSERT INTO STREET_VIEW (street_view_id, segment_id, street_view_url) VALUES (seq_StreetView.nextval,1,'www.google.com');
INSERT INTO ROAD_CONDITION (road_cond_id, segment_id, road_cond_type, road_cond_description, road_cond_start_datetime, road_cond_end_datetime) VALUES (seq_RoadCond.nextval,1,'type','description',TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
-- SELECT TO_CHAR(road_cond_start_date, 'DD-MON-YYYY HH24:MI:SS') AS Start_Time FROM ROAD_CONDITION;
INSERT INTO POINT_OF_INTEREST (poi_id, street_id, poi_name, poi_description, poi_category, poi_loc_id) VALUES (seq_POI.nextval,1,'name','description','category',1);
INSERT INTO INTERSECTION (intersection_id, first_street_id, second_street_id, intersection_loc_id) VALUES (seq_Intersection.nextval,1,1,1);
INSERT INTO INTERSECTING_SEGMENTS (segment_id, intersection_start_id, intersection_end_id) VALUES (1,1,1);
INSERT INTO PEDESTRIAN_WALKWAY (walkway_id, walkway_type, walkway_width, walkway_accessible, walkway_surface) VALUES (seq_PedestrianWalkway.nextval,'type',0.213,'accessible','surface');
INSERT INTO PEDESTRIAN_CROSSING (crossing_id, intersection_id, crossing_type, crossing_lights, crossing_signal) VALUES (seq_PedestrianCrossing.nextval,1,'type','lights','signal');
INSERT INTO PEDESTRIAN_DATA (pdata_id, crossing_id, pdata_datetime, pdata_average_speed, pdata_pedestrian_volume, pdata_congestion_level) VALUES (seq_PedestrianData.nextval,1,TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),0.213,1,1);